@baseUrl = http://localhost:5001

### Estado inicial
GET {{baseUrl}}/contador

### Incrementar 1
PUT {{baseUrl}}/contador

### Incrementar 2
PUT {{baseUrl}}/contador

### Leer después de incrementar
GET {{baseUrl}}/contador

### Borrar contador
DELETE {{baseUrl}}/contador

### Leer valor final
GET {{baseUrl}}/contador
